"""
Alert Schema
------------
Represents a security alert generated by the Rule-Based Detection Engine.
"""

from dataclasses import dataclass, asdict


@dataclass(slots=True)
class Alert:
    """
    Represents a security alert generated by the Rule Engine.
    """

    rule_id: str
    category: str
    source: str
    threat: str
    severity: str
    threat_score: int
    description: str
    timestamp: str

    def to_dict(self) -> dict:
        """
        Convert Alert object into dictionary.
        """
        return asdict(self)